### PR TITLE
feat(require): bind multiple events with single common handler

### PR DESCRIPTION
**Pull request by frostbane**
I was browsing through the Ractive documentation and saw

``` html
<div on-mouseover-mousemove='set( "hover", true )'>...</div>
```

and I thought that

``` html
data-on-childevent1-childevent2-....="parentevent"
<!-- when any of the childeventN is fired parentevent will get fired -->
```

``` html
data-listen-childevent1-childevent2-...="parentevent"
<!-- when parentevent is fired all of the childeventNs will also get fired -->
```

could also be possible.

Here's a sample on how I use it:

``` html
<rv-require name="dataList"
            src="widgets/data-list"
            data-title="等級色分類"
            data-addbtnlabel="追加・変更"
            data-sortable="false"
            data-on-resetdata-cleardata="clear-list-data"
            data-listen-clearselected-resetrange="clear-ranges"></rv-require>
```

### CODE REVIEW

**Comment by XavierBoubert** [comment]
Thanks again @frostbane!

Please can you follow the coding style?

``` javascript
name.split('-').forEach(function(eventName) {
  if (eventName.trim()) {
    events[eventName] = attr.value;
  }
});
```

**Comment by XavierBoubert** [comment]
I have updated the documentation with your work :wink: 

http://ractive-require.codecorico.com/#events

**Comment by frostbane** [comment]
I have refactored the code.

**Comment by XavierBoubert** [comment]
Sorry sorry but a if, even in single ligne needs its brackets. :sweat_smile:

``` javascript
if (eventName.trim()) {
  events[eventName] = attr.value;
}
```

**Comment by XavierBoubert** [comment]
(I prefer to let you correct that to add commits after your work :wink:)

**Comment by XavierBoubert** [comment]
(And strings are always in `'` instead of `"`)

More on the [JSCS rules](https://github.com/CodeCorico/ractive-require/blob/master/.jscsrc)

**Comment by XavierBoubert** [comment]
Perfect!

**Comment by XavierBoubert** [comment]
Released in 0.6.4

**Comment by XavierBoubert** [comment]
0.6.5 in fact.

**Pull request merged**
